services:
  jenkins:
    image: builong99/jenkins:ltr
    build: ./
    volumes:
      - ./home:/root/.jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    tty: true
    network_mode: host